### ISSUE TITLE
Exception during "sudo ./pybombs config"

### ISSUE THREAD

**Issue by ptrkrysik** [gnuradio/pybombs#180]
In current revision of pybombs it is not possible to configure pybombs. Doing:
sudo ./pybombs config

results with:
Initializing config file...
Username for GIT access
gituser [root]:
Directory of git cache repository
gitcache []:
Options to always pass to git clones (--depth=1 or --single-branch will speed up clones)
gitoptions []:
Install Prefix
Traceback (most recent call last):
  File "./pybombs", line 25, in <module>
    from mod_pybombs import verbosity as v
  File "/home/piotr/pybombs/mod_pybombs/__init__.py", line 22, in <module>
    from globals import *;
  File "/home/piotr/pybombs/mod_pybombs/globals.py", line 48, in <module>
    config_init(config);
  File "/home/piotr/pybombs/mod_pybombs/cfg.py", line 70, in config_init
    if os.path.basename(pwd)=="pybombs":
  File "/usr/lib/python2.7/posixpath.py", line 121, in basename
    i = p.rfind('/') + 1

**Comment by ptrkrysik** [comment]
I'm now not sure that pybombs ever was running configuration under sudo. I'm closing the issue then. 

The solution if user doesn't have write access to directory he wants to install to is to first run pybobms config without sudo and then pybombs install with sudo.
