### ISSUE TITLE
Installation failure on OpenSuSe 42.1

### ISSUE THREAD

**Issue by drom** [gnuradio/pybombs#249]
```sh
drom@drom:~/work> pip install PyBOMBS
Collecting PyBOMBS
  Using cached PyBOMBS-2.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ujeo9glo/PyBOMBS/setup.py", line 73, in <module>
        import pybombs
      File "/tmp/pip-build-ujeo9glo/PyBOMBS/pybombs/__init__.py", line 24, in <module>
        from utils import dict_merge
    ImportError: No module named 'utils'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ujeo9glo/PyBOMBS
```

**Comment by mbr0wn** [comment]
I'd guess this doesn't happen anymore. Can you confirm?

    pip install --upgrade git+https://github.com/gnuradio/pybombs.git

**Comment by drom** [comment]
Yes. It works. Thank you.
