### ISSUE TITLE
initial getting of recipes fails if git not preinstalled on Ubuntu 14.04LTS

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/pybombs#276]
Tried this with a virgin 14.04.4LTS VM:
```
sudo apt-get install python-pip
sudo pip install PyBOMBS
pybombs recipes add gr-recipes git+https://github.com/gnuradio/gr-recipes.git
```
fails with:
```
pybombs recipes add gr-recipes git+https://github.com/gnuradio/gr-recipes.git
|
\- git
Traceback (most recent call last):
  File "/usr/local/bin/pybombs", line 9, in <module>
    load_entry_point('PyBOMBS==2.0.1', 'console_scripts', 'pybombs')()
  File "/usr/local/lib/python2.7/dist-packages/pybombs/main.py", line 30, in main
    return dispatch() or 0
  File "/usr/local/lib/python2.7/dist-packages/pybombs/commands/base.py", line 134, in dispatch
    return get_cmd_dict(cmd_list)[args.command](cmd=args.command, args=args).run()
  File "/usr/local/lib/python2.7/dist-packages/pybombs/commands/recipes.py", line 136, in run
    }[self.args.recipe_command]()
  File "/usr/local/lib/python2.7/dist-packages/pybombs/commands/recipes.py", line 189, in _add_recipes
    Fetcher().fetch_url(uri, recipe_cache_top_level, alias, {}) # No args
  File "/usr/local/lib/python2.7/dist-packages/pybombs/fetcher.py", line 72, in fetch_url
    fetcher.assert_requirements()
  File "/usr/local/lib/python2.7/dist-packages/pybombs/requirer.py", line 73, in assert_requirements
    require_hostsys_dependencies(self.host_sys_deps)
  File "/usr/local/lib/python2.7/dist-packages/pybombs/requirer.py", line 47, in require_hostsys_dependencies
    Install('install', args).run()
  File "/usr/local/lib/python2.7/dist-packages/pybombs/commands/install.py", line 143, in run
    if self.cmd == 'install' and self.args.deps_only and pkg in self.args.packages:
AttributeError: 'Namespace' object has no attribute 'deps_only'
```

Works if I `sudo apt-get install git` first.

**Comment by mbr0wn** [comment]
028a2636bb39d35c52127ca52129acb26c4e2e44
