### ISSUE TITLE
TypeError: Error when calling the metaclass bases     multiple bases have instance lay-out conflict

### ISSUE THREAD

**Issue by geofflangenderfer** [gnuradio/pybombs#526]
in my conda env:
python -c "import gnuradio.wxgui.forms" results in:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "forms.py", line 64, in <module>
    class _form_base(pubsub, wx.BoxSizer):
TypeError: Error when calling the metaclass bases
    multiple bases have instance lay-out conflict
```

no conda env:
python2 -c "import gnuradio.wxgui.forms" works correctly

Any ideas how I can solve this?

**Comment by lucaspfernandes** [comment]
Did you fix that ? How ?
